### ISSUE TITLE
Rename "WellsWithTCE Buf10m3D" to "Wells Sampled for TCE"

### ISSUE THREAD

**Issue by froberts** [USEPA/R9-CentralBasin#15]

**Comment by tbock** [comment]
@froberts @GeoFe33 status?

**Comment by GeoFe33** [comment]
We have "TCE Sampling Results" as the name.  This should be closed.  It'd be nice to know specifically which layer (with link) this is referring to.  The naming convention for these layers changed since this issue was raised.
![image](https://user-images.githubusercontent.com/54416878/191804931-c3fdc77d-e4c2-4c75-b6b5-6ac8b5626648.png)

**Comment by tbock** [comment]
Closing as no longer relevant then.
